!!Tasks
tasks:
  view page:
    command: cmd /C start "" "{path}{file}{ext}"
    extensions: [html]
    highlighter: text/html
  git pull:
    command: cmd /C git pull
    extensions: [gitignore]
    highlighter: text/plain
  git push:
    command: cmd /C git add . && git commit -m "{commit message}" && git push
    extensions: [gitignore]
    highlighter: text/plain
  python run:
    command: python {path}{file}{ext}
    extensions: [py]
    highlighter: text/python
